# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\project.json'
    outputType: 'Process'
    orchestratorConnection: 'OrchestratorTokenBasedConnection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
# - task: UiPathTest@2
#   inputs:
#     testTarget: 'TestSet'
#     orchestratorConnection: 'OrchestratorTokenBasedConnection'
#     folderName: 'Shared'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'PBA'
    publishLocation: 'Container'
